# Global constants
IVR_RESULTS = 8 # Number of historical IVR rows
BETA_REFERENCES = ["SPY"]
VOL_ORDER_COLUMN = 15
ST_ORDER_COLUMN = 8
MIN_VOL_LINE = 35
MIN_CORRELATED_CORRELATION = 0.40
MAX_UNCORRELATED_CORRELATION = 0.20
